# -*- coding: utf-8 -*-
"""Feature_Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOafhh5PhGW1f0mL8k4U8CbWkaO8fu4f
"""

import pandas as pd
data =pd.read_csv("Bank.csv")
data.head()
y =data['Personal Loan']
X =data.drop('Personal Loan',axis=1)

from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.model_selection import train_test_split
selector =SelectKBest(score_func=f_classif,k=4)
X_new =selector.fit_transform(X,y)

X_train,X_test,y_train,y_test =train_test_split(X_new,y,
                                               test_size=0.2,random_state=1)

X.head()